[[argtable]]
arch = "aarch64"
git-tree-sha1 = "91af1f68ea3b1c76c41963e8a2168d6a6ebe63b4"
os = "macos"

    [[argtable.download]]
    sha256 = "ab7ce917dfa29d0b405c27f5480aea621ab84e9e6e92d5cc61aa00540bae5bb7"
    url = "https://github.com/JuliaBinaryWrappers/argtable_jll.jl/releases/download/argtable-v2.13.0+0/argtable.v2.13.0.aarch64-apple-darwin.tar.gz"
[[argtable]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "19096bcb569e824649f7556854be5c75a0ef34ca"
libc = "glibc"
os = "linux"

    [[argtable.download]]
    sha256 = "28a4cdffff9e7d167f9aa2f38a0b62cfeb69d3838098c712d25abda0baf13959"
    url = "https://github.com/JuliaBinaryWrappers/argtable_jll.jl/releases/download/argtable-v2.13.0+0/argtable.v2.13.0.aarch64-linux-gnu-cxx03.tar.gz"
[[argtable]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "19096bcb569e824649f7556854be5c75a0ef34ca"
libc = "glibc"
os = "linux"

    [[argtable.download]]
    sha256 = "28a4cdffff9e7d167f9aa2f38a0b62cfeb69d3838098c712d25abda0baf13959"
    url = "https://github.com/JuliaBinaryWrappers/argtable_jll.jl/releases/download/argtable-v2.13.0+0/argtable.v2.13.0.aarch64-linux-gnu-cxx11.tar.gz"
[[argtable]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8227e1e278ae22455dd65a656dc9f3da5749fe8e"
libc = "musl"
os = "linux"

    [[argtable.download]]
    sha256 = "68ea8824d6b8e433ffdbdb94dd0390d7c943313fbd0238938c25944715d44c6f"
    url = "https://github.com/JuliaBinaryWrappers/argtable_jll.jl/releases/download/argtable-v2.13.0+0/argtable.v2.13.0.aarch64-linux-musl-cxx03.tar.gz"
[[argtable]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8227e1e278ae22455dd65a656dc9f3da5749fe8e"
libc = "musl"
os = "linux"

    [[argtable.download]]
    sha256 = "68ea8824d6b8e433ffdbdb94dd0390d7c943313fbd0238938c25944715d44c6f"
    url = "https://github.com/JuliaBinaryWrappers/argtable_jll.jl/releases/download/argtable-v2.13.0+0/argtable.v2.13.0.aarch64-linux-musl-cxx11.tar.gz"
[[argtable]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f5bbe7b6971c29acb5e82bb6a80162307404d532"
libc = "glibc"
os = "linux"

    [[argtable.download]]
    sha256 = "68b782a0f5f7edab184afaf023e03fd1eacd9bbd87a95c3fa352ba7b0de3c804"
    url = "https://github.com/JuliaBinaryWrappers/argtable_jll.jl/releases/download/argtable-v2.13.0+0/argtable.v2.13.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[argtable]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f5bbe7b6971c29acb5e82bb6a80162307404d532"
libc = "glibc"
os = "linux"

    [[argtable.download]]
    sha256 = "68b782a0f5f7edab184afaf023e03fd1eacd9bbd87a95c3fa352ba7b0de3c804"
    url = "https://github.com/JuliaBinaryWrappers/argtable_jll.jl/releases/download/argtable-v2.13.0+0/argtable.v2.13.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[argtable]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "39d65548153837fab1e055bdc9fca66eca433c61"
libc = "musl"
os = "linux"

    [[argtable.download]]
    sha256 = "100d70bea9179626e6b8ae883b66ab3a12ce401c06b404611b23672d74ce0e45"
    url = "https://github.com/JuliaBinaryWrappers/argtable_jll.jl/releases/download/argtable-v2.13.0+0/argtable.v2.13.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[argtable]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "39d65548153837fab1e055bdc9fca66eca433c61"
libc = "musl"
os = "linux"

    [[argtable.download]]
    sha256 = "100d70bea9179626e6b8ae883b66ab3a12ce401c06b404611b23672d74ce0e45"
    url = "https://github.com/JuliaBinaryWrappers/argtable_jll.jl/releases/download/argtable-v2.13.0+0/argtable.v2.13.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[argtable]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fd4477ac209e68ed54f01ac2f7bfe2544d16dee0"
libc = "glibc"
os = "linux"

    [[argtable.download]]
    sha256 = "315b8df8c6864dcebff337fe44be99168322b95722306108002c139944e378a5"
    url = "https://github.com/JuliaBinaryWrappers/argtable_jll.jl/releases/download/argtable-v2.13.0+0/argtable.v2.13.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[argtable]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd4477ac209e68ed54f01ac2f7bfe2544d16dee0"
libc = "glibc"
os = "linux"

    [[argtable.download]]
    sha256 = "315b8df8c6864dcebff337fe44be99168322b95722306108002c139944e378a5"
    url = "https://github.com/JuliaBinaryWrappers/argtable_jll.jl/releases/download/argtable-v2.13.0+0/argtable.v2.13.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[argtable]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b2ef19220df2c1bb67793de8656e41b4adbba157"
libc = "musl"
os = "linux"

    [[argtable.download]]
    sha256 = "9265b8432f70a82f2eb24f318b97b7d9c7c822bb3548d77531263d713c67200d"
    url = "https://github.com/JuliaBinaryWrappers/argtable_jll.jl/releases/download/argtable-v2.13.0+0/argtable.v2.13.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[argtable]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b2ef19220df2c1bb67793de8656e41b4adbba157"
libc = "musl"
os = "linux"

    [[argtable.download]]
    sha256 = "9265b8432f70a82f2eb24f318b97b7d9c7c822bb3548d77531263d713c67200d"
    url = "https://github.com/JuliaBinaryWrappers/argtable_jll.jl/releases/download/argtable-v2.13.0+0/argtable.v2.13.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[argtable]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e1675f16b7452ffe6e0d21a35bf64163fe3e1a50"
libc = "glibc"
os = "linux"

    [[argtable.download]]
    sha256 = "74e7a7aca695a560f026e926b1e09fe15e7e15e53f7d85cc4a0a0a4888fbf6a7"
    url = "https://github.com/JuliaBinaryWrappers/argtable_jll.jl/releases/download/argtable-v2.13.0+0/argtable.v2.13.0.i686-linux-gnu-cxx03.tar.gz"
[[argtable]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e1675f16b7452ffe6e0d21a35bf64163fe3e1a50"
libc = "glibc"
os = "linux"

    [[argtable.download]]
    sha256 = "74e7a7aca695a560f026e926b1e09fe15e7e15e53f7d85cc4a0a0a4888fbf6a7"
    url = "https://github.com/JuliaBinaryWrappers/argtable_jll.jl/releases/download/argtable-v2.13.0+0/argtable.v2.13.0.i686-linux-gnu-cxx11.tar.gz"
[[argtable]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b11bf9612e8ec8a29116c5adc2ed01f35423a9f2"
libc = "musl"
os = "linux"

    [[argtable.download]]
    sha256 = "30287db3f2097d73c12bfc184d608895b833ec9d3d6f568a00a982cef7c485a9"
    url = "https://github.com/JuliaBinaryWrappers/argtable_jll.jl/releases/download/argtable-v2.13.0+0/argtable.v2.13.0.i686-linux-musl-cxx03.tar.gz"
[[argtable]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b11bf9612e8ec8a29116c5adc2ed01f35423a9f2"
libc = "musl"
os = "linux"

    [[argtable.download]]
    sha256 = "30287db3f2097d73c12bfc184d608895b833ec9d3d6f568a00a982cef7c485a9"
    url = "https://github.com/JuliaBinaryWrappers/argtable_jll.jl/releases/download/argtable-v2.13.0+0/argtable.v2.13.0.i686-linux-musl-cxx11.tar.gz"
[[argtable]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b80619194e65c5e3457a75988dc95e8f4914e8c6"
libc = "glibc"
os = "linux"

    [[argtable.download]]
    sha256 = "6bd9f6eb08a82aed65e885a18812f7eb528c38f4390c90396abdbcac895cf7bf"
    url = "https://github.com/JuliaBinaryWrappers/argtable_jll.jl/releases/download/argtable-v2.13.0+0/argtable.v2.13.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[argtable]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b80619194e65c5e3457a75988dc95e8f4914e8c6"
libc = "glibc"
os = "linux"

    [[argtable.download]]
    sha256 = "6bd9f6eb08a82aed65e885a18812f7eb528c38f4390c90396abdbcac895cf7bf"
    url = "https://github.com/JuliaBinaryWrappers/argtable_jll.jl/releases/download/argtable-v2.13.0+0/argtable.v2.13.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[argtable]]
arch = "x86_64"
git-tree-sha1 = "66e87ebe3f8bc2444e3c3559f415a41f05311cb8"
os = "macos"

    [[argtable.download]]
    sha256 = "5eca4e3760cb8f442c6e45af05e365c8e08ebf377f6abb514653a42784fd5a28"
    url = "https://github.com/JuliaBinaryWrappers/argtable_jll.jl/releases/download/argtable-v2.13.0+0/argtable.v2.13.0.x86_64-apple-darwin.tar.gz"
[[argtable]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c097372887c5a2e38aacfdcdf48299610d532551"
libc = "glibc"
os = "linux"

    [[argtable.download]]
    sha256 = "dea79c292602a1afc91dacd955ff2c9a80f83a65b3f563afeb55f89f1922c114"
    url = "https://github.com/JuliaBinaryWrappers/argtable_jll.jl/releases/download/argtable-v2.13.0+0/argtable.v2.13.0.x86_64-linux-gnu-cxx03.tar.gz"
[[argtable]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c097372887c5a2e38aacfdcdf48299610d532551"
libc = "glibc"
os = "linux"

    [[argtable.download]]
    sha256 = "dea79c292602a1afc91dacd955ff2c9a80f83a65b3f563afeb55f89f1922c114"
    url = "https://github.com/JuliaBinaryWrappers/argtable_jll.jl/releases/download/argtable-v2.13.0+0/argtable.v2.13.0.x86_64-linux-gnu-cxx11.tar.gz"
[[argtable]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "30a012c15111f72921676e0675b5bee9e7f515f6"
libc = "musl"
os = "linux"

    [[argtable.download]]
    sha256 = "2a2dfed723642651236da86367e81f23aa4b83f103aee44f9069eb8376fa9153"
    url = "https://github.com/JuliaBinaryWrappers/argtable_jll.jl/releases/download/argtable-v2.13.0+0/argtable.v2.13.0.x86_64-linux-musl-cxx03.tar.gz"
[[argtable]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "30a012c15111f72921676e0675b5bee9e7f515f6"
libc = "musl"
os = "linux"

    [[argtable.download]]
    sha256 = "2a2dfed723642651236da86367e81f23aa4b83f103aee44f9069eb8376fa9153"
    url = "https://github.com/JuliaBinaryWrappers/argtable_jll.jl/releases/download/argtable-v2.13.0+0/argtable.v2.13.0.x86_64-linux-musl-cxx11.tar.gz"
[[argtable]]
arch = "x86_64"
git-tree-sha1 = "e2080f4184b9bdd8a4fd7108297dff398b297f6d"
os = "freebsd"

    [[argtable.download]]
    sha256 = "ba1784ec5752c8d599a076399c65c421a80100790beb63d9747fbbf8a8af28d6"
    url = "https://github.com/JuliaBinaryWrappers/argtable_jll.jl/releases/download/argtable-v2.13.0+0/argtable.v2.13.0.x86_64-unknown-freebsd.tar.gz"
