# Autogenerated wrapper script for argtable_jll for x86_64-apple-darwin
export libargtable3

JLLWrappers.@generate_wrapper_header("argtable")
JLLWrappers.@declare_library_product(libargtable3, "@rpath/libargtable3.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libargtable3,
        "lib/libargtable3.0.0.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
